using System;
using System.Collections;
using System.Collections.Generic;


namespace VTMS.Model.Entities
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Customer 
	{
		#region Private Members
		
		// Primary Key(s) 
		private int _id; 
		
		// Properties 
        private string _userid;
		private string _name; 
		private string _phone; 
		private string _address; 		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Customer()
		{
			_id = 0; 
			_name = null; 
			_phone = null; 
			_address = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Customer(int id, string name, string phone, string address)
		{
			_id = id; 
			_name = name; 
			_phone = phone; 
			_address = address; 
		}
		
		#endregion // End Full Constructor
		
		#region Required Fields Only Constructor
		
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public Customer(int id, string name)
		{
			_id = id; 
			_name = name; 
			_phone = null; 
			_address = null; 
		}
		
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual int Id
		{
			get { return _id; }
			set	
			{
                _id = value;
			}
		}

        /// <summary>
        /// 
        /// </summary>		
        public virtual string UserId
        {
            get { return _userid; }
            set
            {
                _userid = value;
            }
        } 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual string Name
		{
			get { return _name; }
			set	
			{
                _name = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual string Phone
		{
			get { return _phone; }
			set	
			{
                _phone = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual string Address
		{
			get { return _address; }
			set	
			{
                _address = value;
			}
		} 
		#endregion 		
	}
}